[project]
name = "llm-code-review"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "google-cloud-storage>=3.14.1",
    "httpx>=0.28.1",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
